baseURL = 'https://daros.dev/'
languageCode = 'en-us'
title = 'daros.dev'
theme = 'paper'

[params]
  # header social icons
  github = 'ldaros'
  linkedin = 'darosluan'

  # home page profile
  name = 'Luan Daros'
  bio = 'Software Engineer, Hobbyist Game Developer, and Open Source Enthusiast'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
